### PR TITLE
1.2.0.1

### PR DESCRIPTION
**Pull request by StevenDiviney**
## Changes
- Second go now that custom fields have been decided / added
- Universal app support
- And of course "various bug fixes and improvements"

## Reviewers
@a1cooke @pierrezen @tecknut

### FYI
@maximeprades
Tickets will look like the following with:
"----------
Sent from Remember the Date"
inserted at the bottom to show that additional info can be added to the ticket. Does this look ok? 

I will wait for a :+1: from you.

### CODE REVIEW

**Comment by maximeprades** [comment]
not sure I fully understand

what do you mean by "Second go now that custom fields have been decided / added" ?

Also can we add a few custom fields? instead of "showing info can be added" why don't we add a few fake info? Can we add a custom field or two?

**Comment by StevenDiviney** [comment]
Sorry for being unclear, I meant this is the second pull request for Remember the Date updated SDK 1.2. We were waiting for clarification on what kind of information to set in the custom fields.

Custom fields have been added and they show up in lotus :)

**Comment by StevenDiviney** [comment]
I included the screen shot because we showcase custom fields, tags and additional information. The additional info is the only one visible to the user so I just wanna check you think it looks ok.

**Comment by maximeprades** [comment]
ok i'm still confused but i don't have time this week to be confused :)

:+1: 

i'll probably ask you for a testflight version to test it out first

thanks

**Pull request merged**
