### PR TITLE
Updating to 1.2.0.1 and adding universal app changes

### PR DESCRIPTION
**Pull request by StevenDiviney**
## Changes
- Updated to SDK 1.2.0.1
- Merged in universal app changes.

## Reviewers
@a1cooke @pierrezen @tecknut

### FYI
@maximeprades

### CODE REVIEW

**Comment by maximeprades** [comment]
does that also add iPad support?

**Comment by StevenDiviney** [comment]
Yup, universal app = ipad and iphone.

**Comment by tecknut** [comment]
:+1:

**Comment by maximeprades** [comment]
awesome :+1:

**Comment by StevenDiviney** [comment]
Holding off on merge until we decided how we want to use custom fields.

**Pull request closed without merging**
